paths:
  data: data
  collections: content
  layouts: layouts
  static: static
  uploads: static/images
  includes: layouts
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: wysiwyg
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/page.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  articles:
    path: content/blog
    output: true
    icon: article
    preview:
      subtext:
        - template: '{"Draft"|if=draft}'
        - template: '{date|date_long}'
        - key: url
      image:
        - key: thumbImg.image_path
      metadata:
        - text:
            - key: author
          icon: person
    _enabled_editors:
      - content
      - visual
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  data:
    path: data
    output: false
    icon: settings
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
_inputs:
  content:
    type: markdown
    cascade: true
  icon:
    type: select
    options:
      allow_empty: true
      values:
        - ph-user-square
    cascade: true
  description:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      bold: true
      image_size_attributes: true
      italic: true
      link: true
      removeformat: true
    cascade: true
  isActive:
    type: switch
    cascade: true
  social[*].icon:
    type: select
    options:
      allow_empty: true
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
    cascade: true
  page_description:
    type: text
    comment: If empty, defaults to the description set in the Site SEO data file
    cascade: true
  canonical_url:
    type: text
    comment: If empty, defaults to the URL of the page
    cascade: true
  featured_image:
    type: auto
    comment: If empty, defaults to the image set in the Site SEO data file
    cascade: true
  featured_image.image:
    type: image
    options:
      resize_style: crop
      width: 1296
    cascade: true
  thumb_image.image:
    type: image
    options:
      resize_style: crop
      width: 500
      height: 413
    cascade: true
  author_twitter_handle:
    type: twitter
    comment: Defaults to the twitter site value set in the Site SEO data file
    cascade: true
  no_index:
    type: checkbox
    comment: >-
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
    cascade: true
  open_graph_type:
    type: select
    options:
      allow_empty: true
      values:
        - website
        - article
        - profile
    cascade: true
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
    cascade: true
  favicon_image:
    type: image
    comment: For the icon meta tag
    cascade: true
  enable_dropdown:
    type: switch
    cascade: true
  dropdown:
    type: array
    options:
      structures: _structures.dropdown
    label: Dropdown Items
    hidden: '!enable_dropdown'
    cascade: true
  dropdown_link:
    type: url
    label: Link
    cascade: true
  dropdown_text:
    type: text
    label: Name
    cascade: true
  items:
    type: array
    options:
      structures: _structures.items
    cascade: true
  logo:
    type: image
    cascade: true
  categories:
    type: multiselect
    options:
      empty_type: array
      values: data.blog-tags
    cascade: true
  twitter_site:
    type: twitter
    label: Twitter Username
    cascade: true
  logo_url:
    type: auto
    comment: Link for the logo in the top left of the footer
    cascade: true
  copyright:
    type: auto
    comment: Automatically prefixed with the current year
    cascade: true
  enable_nav_btn:
    type: switch
    label: Enable Navigation Button
    cascade: true
  nav_btn:
    type: auto
    label: Navigation Button
    hidden: '!enable_nav_btn'
    cascade: true
  thumbImg:
    type: auto
    label: Thumbnail Image
    cascade: true
  featuredImg:
    type: auto
    label: Featured Image
    cascade: true
  image_alt:
    type: auto
    label: Image Description
    cascade: true
_structures:
  content_blocks:
    style: modal
    values: []
  dropdown:
    style: select
    values:
      - value:
          dropdown_text:
          dropdown_link:
  social:
    style: select
    values:
      - value:
          link:
          icon:
  sections:
    style: select
    values:
      - value:
          title:
          links:
  links:
    style: select
    values:
      - value:
          link:
          text:
  features:
    style: select
    values:
      - value:
          item:
          isActive:
  items:
    style: select
    values:
      - value:
          link:
          text:
          enable_dropdown:
          dropdown:
data_config:
  blog-tags: true
timezone: Etc/UTC
